### ISSUE TITLE
项目搭建

### ISSUE THREAD

**Issue by LiLovewei** [hiroi-sora/RapidOCR-json#1]
请大佬指点下，项目怎么搭建

**Comment by hiroi-sora** [comment]
你可以参考 [源项目RapidOcrOnnx](https://github.com/RapidAI/RapidOcrOnnx) 的编译说明，先编译并跑通源项目Demo，然后将本项目的代码移进去。

**Comment by hiroi-sora** [comment]
已更新 [构建指南](https://github.com/hiroi-sora/RapidOCR-json/tree/main/cpp) ，跟着操作即可。
