### ISSUE TITLE
是否有退出命令

### ISSUE THREAD

**Issue by 165149324** [hiroi-sora/RapidOCR-json#10]
如题

**Comment by 165149324** [comment]
就是连续输入 没有退出命令

**Comment by hiroi-sora** [comment]
exe本身没有退出指令。因为它是作为调用方的子进程来运行，想要退出时，父进程直接kill掉子进程就行了。

python接口的话，可以用 ocr.stop() 来终止进程。本质上也是直接kill掉子进程。
