### ISSUE TITLE
【性能问题】运行ocr时CPU占用过高

### ISSUE THREAD

**Issue by NakanoSanku** [hiroi-sora/RapidOCR-json#11]
运行环境: 
语言: Python 3.10
系统: Windows10 ltsc
测试环境:
-  i5 4590 ocr识别1280x720灰度图像，CPU占用峰值达到70％，最低也将近35％，平均50％
-  r5 4600u ocr识别1280x720灰度图像，CPU占用峰值达到50％，最低也将近30％，平均未知
尝试设置线程数为1后问题依旧，这个负载是正常？有什么合适的解决思路吗，thanks

**Comment by hiroi-sora** [comment]
这是正常的，CPU占用越高说明算法的多线程设计越合理，能“充分榨干硬件机能”以提高任务速度。其实Rapid onnx引擎还不算最优化，隔壁Paddle在启用mkldnn加速后，可以全核心占用90%以上。因此Paddle的任务速度也比Rapid更快。

将线程数设为1后，你开任务管理器查看每个逻辑核的占用，应该只有一个核心占用高。win10的CPU总体占用值不一定准，得看单个核的占用。

**Comment by NakanoSanku** [comment]
> 这是正常的，CPU占用越高说明算法的多线程设计越合理，能“充分榨干硬件机能”以提高任务速度。其实Rapid onnx引擎还不算最优化，隔壁Paddle在启用mkldnn加速后，可以全核心占用90%以上。因此Paddle的任务速度也比Rapid更快。
> 
> 将线程数设为1后，你开任务管理器查看每个逻辑核的占用，应该只有一个核心占用高。win10的CPU总体占用值不一定合理，得看单个核的占用。

thanks
