### ISSUE TITLE
大佬您好，想请问一下模型更新的问题

### ISSUE THREAD

**Issue by Leowolf93** [hiroi-sora/RapidOCR-json#17]
我一直在用您的json在本地去做图片识别，json输出的方式非常好用！
有一些疑问，希望能得到您的回答，非常感谢！
1、应该是有识别语种的功能的，假设存在中英文混杂这种情况，它判断的方式是什么呢？
2、在models下的onnx模型我看有一些都是22年23年的模型了，去哪里更新它呢？

**Comment by hiroi-sora** [comment]
你好。

#### 1. 模型本身并不能“判断语种”。

比如，**中英文通用模型** 实际上是“同时学习了两种语言的特征”，而不是能“区分两种语言”。可参考：

https://github.com/hiroi-sora/PaddleOCR-json/issues/75

#### 2. 关于模型：

RapidOCR 使用的就是 PaddleOCR 的模型，不过模型文件需要转换一下格式。

RapidOCR 更新模型的步骤是：

1. 前往 [PP-OCR系列模型列表](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/models_list.md) ，下载Paddle模型。注意，文件名中含`v2`、`v3`的都是几年前的，只有`v4`是最新的。另外，一套完整的OCR模型，包含检测`det`、方向分类`cls`、识别`rec`这三个子模型。
2. 将下载后的Paddle模型文件，通过 [PaddleOCRModelConvert](https://github.com/RapidAI/PaddleOCRModelConvert) 转换为onnx格式。
3. 将onnx模型文件，扔进本项目的目录下。启动 `RapidOCR-json.exe` 时，传参传入模型路径即可，具体见文档。
