### ISSUE TITLE
请问命令行操作中，怎么单独把text提取出来？

### ISSUE THREAD

**Issue by Leroy-X** [hiroi-sora/RapidOCR-json#3]
如题，非常感谢QQ

**Comment by hiroi-sora** [comment]
程序的输出值是json字符串，因此需要json解析库来进行解析并提取出text字段。

大部分编程语言都提供了json解析库。你应该使用编程手段来调用这个exe，而不是直接在控制台手动调用它。可参考隔壁 [PaddleOCR-json的调用方式](https://github.com/hiroi-sora/PaddleOCR-json#api%E5%88%97%E8%A1%A8) 。

如果你确实希望只是在控制台调用OCR并直接获取返回值，请使用 [Umi-OCR](https://github.com/hiroi-sora/Umi-OCR) ，它提供了更直观的 [命令行指令](https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/README_CLI.md) 。

**Comment by Leroy-X** [comment]
好的，非常感谢

**Comment by Leroy-X** [comment]
用gpt写了一个[批处理文件](https://github.com/Leroy-X/EasyOCR-batch-file)，使用的jq提取文本内容。
