### ISSUE TITLE
win7 32位

### ISSUE THREAD

**Issue by zhaodongyang2016** [hiroi-sora/RapidOCR-json#4]
作者您好，这个工程可在windows 32位上运行吗，我们有一些客户是老旧的win7 32位系统。但软件不得不运行在他们的设备上。您有测试过onnxruntime的方案在win7 32位上的可行性吗。您的RapidOCR不胜感激！

**Comment by hiroi-sora** [comment]
本项目是基于 [RapidOcrOnnx](https://github.com/RapidAI/RapidOcrOnnx) 的二次开发。Rapid项目本身是支持32位的。你可以先尝试，将Rapid官方工程编译为32位。如果调试正常，那么本项目也可以用相同的方式编译32位。

Rapid的编译说明： https://github.com/RapidAI/RapidOcrOnnx/blob/main/BUILD.md

本项目的编译说明： https://github.com/hiroi-sora/RapidOCR-json/blob/main/cpp/README.md

编译本项目时需要注意：
1. 不能用本仓库中提供的 lib.7z 。需要自行下载32位版的onnxruntime-static与opencv-static。
2. 打开 [generate-vs-project.bat](https://github.com/hiroi-sora/RapidOCR-json/blob/main/cpp/generate-vs-project.bat) ，第50行的flag修改为 =1 。
