### ISSUE TITLE
[problem] 能不能自定义模型?

### ISSUE THREAD

**Issue by NakanoSanku** [hiroi-sora/RapidOCR-json#5]
特殊需求，通用的ocr模型不能太满足，是否能够自行训练自定义模型使用呢，如果可以能不能简单说说食用方案，对cpp懂的不多

**Comment by hiroi-sora** [comment]
模型训练并不需要cpp，用的是python。

首先需要训练Paddle模型： https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/training.md

然后转为Onnx格式以便导入Rapid： https://github.com/RapidAI/PaddleOCRModelConvert

**Comment by NakanoSanku** [comment]
抱歉，是我漏看了models参数，thanks
