### ISSUE TITLE
指令说明和 python api调用问题

### ISSUE THREAD

**Issue by lichengying** [hiroi-sora/RapidOCR-json#6]
你好，请问我在使用过程中，想先修改RapidOCR-json.exe的指令说明值，然后再使用python api进行调用，是不是只能重新构建RapidOCR-json.exe？因为我在测试过程中修改RapidOCR-json.exe的指令说明值后用python demo1.py运行代码，但没有发生变化。

**Comment by hiroi-sora** [comment]
请问“指令说明值”指的是什么

**Comment by lichengying** [comment]
![QQ截图20231220112844](https://github.com/hiroi-sora/RapidOCR-json/assets/39320411/954cf32f-fb6e-4875-b089-63335ddf028e)
就是这些ensureAscii，比如我想把文字方向检测和角度投票设为0，./RapidOCR-json.exe （--省略其他设置值--）--doAngle=0 --mostAngle=0，再使用python的api调用

**Comment by hiroi-sora** [comment]
哦哦，这当然不用重新编译。调用py api时传入参数即可。如：

ocr = OcrAPI(ocrPath, argsStr=" --doAngle=0 --mostAngle=0")

**Comment by lichengying** [comment]
好的，非常感谢
