### ISSUE TITLE
关于精准度问题

### ISSUE THREAD

**Issue by L1nJin** [hiroi-sora/RapidOCR-json#8]
您好作者，在测试过程中，我发现部分图片（字体反光、倾斜角度等）识别精准度有点低，请问应该如何调节呢？

**Comment by hiroi-sora** [comment]
这类非清晰图片确实是OCR的难点。Paddle系列模型对非清晰图片的准确度已经是开源领域中较为领先的了，如果你追求更高的精准度，可能需要寻求付费的商业高精度OCR服务，比如百度腾讯等提供的服务。

如果你有大量素材，也可以尝试自己训练高精度垂类模型。参考  https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/training.md

**Comment by L1nJin** [comment]
好的谢谢指导
